import { StyleSheet } from 'react-native';
import { COLORS, FONTS, FONT_SIZES, SPACING } from '../../constants/theme';

export const paywallStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: COLORS.cream },
  heroGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 380,
  },
  safe: { flex: 1 },
  closeBtn: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: SPACING.sm,
  },
  scrollContent: {
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.xxl,
  },
  hero: {
    alignItems: 'center',
    paddingTop: SPACING.lg,
    paddingBottom: SPACING.lg,
  },
  heroEmoji: { fontSize: 64, marginBottom: SPACING.md },
  heroTitle: {
    fontFamily: FONTS.displayBold,
    fontSize: 32,
    color: COLORS.white,
    textAlign: 'center',
    marginBottom: SPACING.sm,
  },
  heroSubtitle: {
    fontFamily: FONTS.bodyRegular,
    fontSize: FONT_SIZES.body,
    color: 'rgba(255, 255, 255, 0.92)',
    textAlign: 'center',
    lineHeight: 22,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 24,
    marginBottom: SPACING.lg,
  },
  cardTitle: {
    fontFamily: FONTS.bodyBold,
    fontSize: FONT_SIZES.body,
    color: COLORS.textPrimary,
    marginBottom: SPACING.md,
  },
  featureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SPACING.sm,
  },
  featureIcon: { marginRight: SPACING.sm },
  featureText: {
    fontFamily: FONTS.bodyRegular,
    fontSize: 15,
    color: COLORS.textPrimary,
    flex: 1,
  },
  plansRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: SPACING.lg,
  },
  planCard: {
    width: '48%',
    borderRadius: 12,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
    alignItems: 'center',
  },
  planCardBestBg: { backgroundColor: '#FFFDF5' },
  planCardSelected: {
    borderColor: COLORS.primaryGold,
    borderWidth: 2,
  },
  bestBadge: {
    position: 'absolute',
    top: -8,
    right: 8,
    backgroundColor: COLORS.primaryGold,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 3,
    borderRadius: 999,
  },
  bestBadgeText: {
    fontFamily: FONTS.bodyBold,
    fontSize: 10,
    color: COLORS.white,
  },
  planLabel: {
    fontFamily: FONTS.bodyBold,
    fontSize: FONT_SIZES.body,
    color: COLORS.textPrimary,
    marginBottom: 4,
  },
  planPrice: {
    fontFamily: FONTS.bodyMedium,
    fontSize: 14,
    color: COLORS.textPrimary,
  },
  planPriceStrike: {
    fontFamily: FONTS.bodyRegular,
    fontSize: 12,
    color: COLORS.textSecondary,
    textDecorationLine: 'line-through',
  },
  planSaving: {
    fontFamily: FONTS.bodyMedium,
    fontSize: 12,
    color: COLORS.successGreen,
    marginTop: 4,
  },
  cta: {
    backgroundColor: COLORS.primaryGold,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: SPACING.md,
  },
  ctaText: {
    fontFamily: FONTS.bodyBold,
    fontSize: 18,
    color: COLORS.white,
  },
  restoreBtn: { alignItems: 'center', paddingVertical: SPACING.sm },
  restoreText: {
    fontFamily: FONTS.bodyRegular,
    fontSize: 14,
    color: COLORS.textSecondary,
    textDecorationLine: 'underline',
  },
  legal: {
    fontFamily: FONTS.bodyRegular,
    fontSize: 11,
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginTop: SPACING.md,
    lineHeight: 16,
  },
  legalLinks: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: SPACING.sm,
  },
  legalLink: {
    fontFamily: FONTS.bodyRegular,
    fontSize: 11,
    color: COLORS.textSecondary,
    textDecorationLine: 'underline',
  },
  legalDivider: {
    color: COLORS.textSecondary,
    marginHorizontal: 8,
    fontSize: 11,
  },
  loadingWrap: { paddingVertical: SPACING.xxl, alignItems: 'center' },
  errorCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: SPACING.lg,
    alignItems: 'center',
    marginTop: SPACING.lg,
  },
  errorTitle: {
    fontFamily: FONTS.bodyBold,
    fontSize: FONT_SIZES.body,
    color: COLORS.textPrimary,
    textAlign: 'center',
    marginBottom: SPACING.sm,
  },
  errorBody: {
    fontFamily: FONTS.bodyRegular,
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginBottom: SPACING.md,
  },
  retryBtn: {
    backgroundColor: COLORS.primaryGold,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.xl,
    borderRadius: 999,
  },
  retryText: {
    fontFamily: FONTS.bodyBold,
    color: COLORS.white,
    fontSize: FONT_SIZES.body,
  },
  socialRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: SPACING.lg,
  },
  socialText: {
    fontFamily: FONTS.bodyMedium,
    fontSize: 14,
    color: COLORS.white,
    marginRight: SPACING.sm,
  },
  socialStars: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  socialStarText: {
    fontFamily: FONTS.bodyBold,
    fontSize: 14,
    color: COLORS.white,
    marginLeft: SPACING.xs,
  },
  testimonial: {
    marginBottom: SPACING.md,
  },
  testimonialText: {
    fontFamily: FONTS.displayRegular,
    fontSize: FONT_SIZES.body,
    color: COLORS.textPrimary,
    lineHeight: 22,
  },
  testimonialAuthor: {
    fontFamily: FONTS.bodyMedium,
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: SPACING.xs,
  },
  countdownBar: {
    backgroundColor: 'rgba(13, 13, 43, 0.45)',
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: 999,
    alignSelf: 'center',
    marginTop: SPACING.sm,
  },
  countdownText: {
    fontFamily: FONTS.bodyBold,
    color: COLORS.white,
    fontSize: 13,
  },
});
